# Generated by Django 4.2 on 2023-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='body',
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='brief',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='like',
            field=models.IntegerField(default=17573),
        ),
    ]
