# Generated by Django 4.2 on 2023-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_articleinfo_body_articleinfo_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='like',
            field=models.IntegerField(default=2044),
        ),
    ]
