# Generated by Django 4.2 on 2023-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articleinfo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='like',
            field=models.IntegerField(default=1691),
        ),
    ]
