# Generated by Django 4.2 on 2023-08-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articleinfo_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='category',
            field=models.CharField(default='', max_length=10),
        ),
    ]
