# Generated by Django 4.2 on 2023-08-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_comment_options_remove_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_time']},
        ),
    ]
