# Generated by Django 4.2 on 2023-09-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articleinfo',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
